# Generated by Django 3.2.12 on 2023-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
