# Generated by Django 3.2.12 on 2023-12-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231217_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
