# Generated by Django 3.2.12 on 2023-12-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231217_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
