# Generated by Django 3.2.12 on 2023-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231220_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
