# Generated by Django 3.2.12 on 2023-12-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_clients_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='user_permissions',
        ),
    ]
