# Generated by Django 3.2.12 on 2023-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20231220_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('image', models.ImageField(default=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='adresse',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
