# Generated by Django 3.2.12 on 2023-12-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20231221_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produits',
        ),
    ]
