# Generated by Django 3.2.12 on 2024-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_alter_clients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('image', models.ImageField(default=True, upload_to='images')),
                ('latitude', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('emballé', models.DateField(auto_now_add=True)),
                ('arrivée_dépôt', models.DateField(default='', max_length=150)),
                ('départ_dépôt', models.DateField(default='', max_length=150)),
                ('date_livraison', models.DateField(default='', max_length=150)),
                ('reçu_le', models.DateField(default='', max_length=150)),
                ('destinataire', models.ManyToManyField(blank=True, related_name='destinataire', to='home.clients')),
                ('expéditeur', models.ManyToManyField(related_name='expéditeur', to='home.clients')),
                ('transporteur', models.ManyToManyField(related_name='transporteur', to='home.clients')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
