# Generated by Django 3.2.12 on 2024-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='arrivée_dépôt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='départ_dépôt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='reçu_le',
            field=models.DateField(blank=True, null=True),
        ),
    ]
