# Generated by Django 4.0 on 2023-11-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produits',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
