# Generated by Django 4.0 on 2023-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='image',
            field=models.ImageField(default=10, upload_to='images'),
            preserve_default=False,
        ),
    ]
