# Generated by Django 3.2.12 on 2024-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_auto_20240107_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
